# =========================
# Development stage with hot reload
# =========================
FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache ca-certificates git

RUN go install github.com/air-verse/air@v1.61.0

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8000

CMD ["air", "-c", ".air.toml"]
